<?php

namespace BO\BackOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PianoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PianoRepository extends EntityRepository
{
}
