bo_back_office_homepage:
    pattern:  /
    defaults: { _controller: BOBackOfficeBundle:Default:index }

BOBackOfficeBundle_customer:
    resource:  "@BOBackOfficeBundle/Resources/config/routing/customer.yml"
    prefix:     /customer

BOBackOfficeBundle_piano:
    resource:  "@BOBackOfficeBundle/Resources/config/routing/piano.yml"
    prefix:     /piano