parameters:
#    bo_back_office.example.class: BO\BackOfficeBundle\Example

services:
#    bo_back_office.example:
#        class: %bo_back_office.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
