BO\BackOfficeBundle\Entity\Bill:
    type: entity
    table: null
    repositoryClass: BO\BackOfficeBundle\Entity\BillRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        billNumber:
            type: integer
        content:
            type: string
            length: 255
        price:
            type: integer
        createdDate:
            type: datetime
        payDate:
            type: datetime
    manyToOne:
        customer:
            targetEntity: Customer
    lifecycleCallbacks: {  }
